export const ReviewsData = [
  {
    id: 1,
    note: 5,
    scale: 5,
    name: 'Debora Wurm',
    title: 'Un accueil formidable',
    comment: 'Brigitte réserve un accueil formidable dans une superbe maison chaleureuse, avec des chambres fraîches et une literie de grande qualité.',
    date: 'Juillet 2026',
    source: 'Google',
    sourceUrl: 'https://www.google.com/travel/search?q=la%20berjotine&ap=ugEHcmV2aWV3cw',
  },
  {
    id: 2,
    note: 5,
    scale: 5,
    name: '481h_l_nei',
    title: 'Une pause enchantée',
    comment: 'Un excellent accueil, une décoration pleine de charme et un délicieux petit déjeuner composé de produits frais et maison.',
    date: 'Il y a un an',
    source: 'Tripadvisor',
    sourceUrl: 'https://www.tripadvisor.fr/Hotel_Review-g651706-d8467429-Reviews-La_Berjotine-Charolles_Saone_et_Loire_Bourgogne_Franche_Comte.html',
  },
  {
    id: 3,
    note: 5,
    scale: 5,
    name: 'Hélène Imberdis',
    title: 'Belle découverte dans le Charolais',
    comment: 'Une hôte charmante, une maison ancienne qui marie élégamment tradition et modernité, une chambre confortable et un petit déjeuner divin.',
    date: 'Juin 2025',
    source: 'Google',
    sourceUrl: 'https://www.google.com/travel/search?q=la%20berjotine&ap=ugEHcmV2aWV3cw',
  }
]
