import Head from 'next/head'
import Homepage from '@/components/Homepage'
import About from '@/components/About'
import Slider from '@/components/Slider'
import Instagram from '@/components/Instagram'
import { SliderData } from '@/components/SliderData'
import Rooms from '@/components/Rooms'
import Reviews from '@/components/Reviews'

export default function Home() {
  return (
    <>
      <Head>
        <title>La Berjotine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
      {/* <Slider slides={SliderData} /> */}
      <About />
      <Rooms />
      <Reviews />
      <Instagram />
    </>
  )
}
